### ISSUE TITLE
Failed to install sqlite3 module correctly: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Emanon42** [thelounge/thelounge-deb#69]
Host OS: Ubuntu 20.04 LTS
Node.js version: v14.16.0
My server is using Cloudflare CDN proxy, SSL/TLS encryption mode is Full (strict). I'm using `certbot` for free TLS certification.
Error message: 
```
$ sudo apt install ./thelounge_4.2.0_all.deb

Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_10.19.0~dfsg-3ubuntu1_amd64.deb ...
Unpacking nodejs (10.19.0~dfsg-3ubuntu1) ...
Selecting previously unselected package thelounge.
Preparing to unpack .../thelounge_4.2.0_all.deb ...
Unpacking thelounge (4.2.0) ...
Setting up libc-ares2:amd64 (1.15.0-1build1) ...
Setting up libnode64:amd64 (10.19.0~dfsg-3ubuntu1) ...
Setting up nodejs-doc (10.19.0~dfsg-3ubuntu1) ...
Setting up nodejs (10.19.0~dfsg-3ubuntu1) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
Setting up thelounge (4.2.0) ...
Downloading sqlite3 module for your specific installation
yarn install v1.22.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/bcryptjs: unable to get local issuer certificate".
info If you think this is a bug, please open a bug report with the information provided in "/usr/lib/node_modules/thelounge/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[!!] Failed to install sqlite3 module correctly, The Lounge will continue working, but you might want to fix this.
Removing leftover files
Creating thelounge group
Creating thelounge user
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
```
My `/usr/lib/node_modules/thelounge/yarn-error.log`: 
```
Arguments:
  /usr/bin/node /usr/lib/node_modules/thelounge/node_modules/yarn/bin/yarn.js --cache-folder /usr/lib/node_modules/thelounge/debian_postinst_yarn_cache --cwd /usr/lib/node_modules/thelounge --non-interactive --no-default-rc --production

PATH:
  /usr/sbin:/usr/bin:/sbin:/bin

Yarn version:
  1.22.4

Node version:
  10.19.0

Platform:
  linux x64

Trace:
  Error: unable to get local issuer certificate
      at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
      at TLSSocket.emit (events.js:198:13)
      at TLSSocket._finishInit (_tls_wrap.js:636:8)

npm manifest:
  {
    "_from": "thelounge@4.2.0",
    "_id": "thelounge@4.2.0",
    "_inBundle": false,
    "_integrity": "sha512-5hijX1V/4CrgrkqCqtwP32LSbLPSF/10nneI+2doPHKx7AdCgR52HqWZo0AQEPv4fvOqEOMLJ0c9pL6t/jUDwg==",
    "_location": "/thelounge",
    "_phantomChildren": {},
    "_requested": {
      "type": "version",
      "registry": true,
      "raw": "thelounge@4.2.0",
      "name": "thelounge",
      "escapedName": "thelounge",
      "rawSpec": "4.2.0",
      "saveSpec": null,
      "fetchSpec": "4.2.0"
    },
    "_requiredBy": [
      "#USER"
    ],
    "_resolved": "https://registry.npmjs.org/thelounge/-/thelounge-4.2.0.tgz",
    "_shasum": "e9b572dd6345c2d0aa13e2a7a48f6b21ab7d1cb8",
    "_spec": "thelounge@4.2.0",
    "_where": "/home/xpaw/thelounge-deb",
    "bin": {
      "thelounge": "index.js"
    },
    "bugs": {
      "url": "https://github.com/thelounge/thelounge/issues"
    },
    "bundleDependencies": false,
    "dependencies": {
      "bcryptjs": "2.4.3",
      "busboy": "0.3.1",
      "chalk": "4.1.0",
      "cheerio": "1.0.0-rc.3",
      "commander": "6.0.0",
      "express": "4.17.1",
      "file-type": "14.7.1",
      "filenamify": "4.1.0",
      "got": "11.5.2",
      "irc-framework": "4.9.0",
      "is-utf8": "0.2.1",
      "ldapjs": "2.1.1",
      "linkify-it": "3.0.2",
      "lodash": "4.17.20",
      "mime-types": "2.1.27",
      "node-forge": "0.9.1",
      "package-json": "6.5.0",
      "read": "1.0.7",
      "read-chunk": "3.2.0",
      "semver": "7.3.2",
      "socket.io": "2.3.0",
      "sqlite3": "5.0.0",
      "tlds": "1.208.0",
      "ua-parser-js": "0.7.21",
      "uuid": "8.3.0",
      "web-push": "3.4.4",
      "yarn": "1.22.4"
    },
    "deprecated": false,
    "description": "The self-hosted Web IRC client",
    "devDependencies": {
      "@babel/core": "7.11.1",
      "@babel/preset-env": "7.11.0",
      "@fortawesome/fontawesome-free": "5.14.0",
      "@vue/server-test-utils": "1.0.3",
      "@vue/test-utils": "1.0.3",
      "babel-loader": "8.1.0",
      "babel-plugin-istanbul": "6.0.0",
      "chai": "4.2.0",
      "copy-webpack-plugin": "6.0.3",
      "css-loader": "4.2.1",
      "cssnano": "4.1.10",
      "dayjs": "1.8.33",
      "emoji-regex": "9.0.0",
      "eslint": "7.7.0",
      "eslint-config-prettier": "6.11.0",
      "eslint-plugin-vue": "6.2.2",
      "fuzzy": "0.1.3",
      "husky": "4.2.5",
      "mini-css-extract-plugin": "0.10.0",
      "mocha": "8.1.1",
      "mousetrap": "1.6.5",
      "normalize.css": "8.0.1",
      "npm-run-all": "4.1.5",
      "nyc": "15.1.0",
      "postcss-import": "12.0.1",
      "postcss-loader": "3.0.0",
      "postcss-preset-env": "6.7.0",
      "prettier": "2.0.5",
      "pretty-quick": "2.0.1",
      "primer-tooltips": "2.0.0",
      "sinon": "9.0.3",
      "socket.io-client": "2.3.0",
      "stylelint": "13.6.1",
      "stylelint-config-standard": "20.0.0",
      "textcomplete": "0.18.2",
      "undate": "0.3.0",
      "vue": "2.6.11",
      "vue-loader": "15.9.3",
      "vue-router": "3.4.3",
      "vue-server-renderer": "2.6.11",
      "vue-template-compiler": "2.6.11",
      "vuedraggable": "2.24.0",
      "vuex": "3.5.1",
      "webpack": "4.44.1",
      "webpack-cli": "3.3.12",
      "webpack-dev-middleware": "3.7.2",
      "webpack-hot-middleware": "2.25.0"
    },
    "engines": {
      "node": ">=10.15.0"
    },
    "homepage": "https://thelounge.chat/",
    "husky": {
      "hooks": {
        "pre-commit": "pretty-quick --staged"
      }
    },
    "keywords": [
      "lounge",
      "browser",
      "web",
      "chat",
      "client",
      "irc",
      "server",
      "thelounge"
    ],
    "license": "MIT",
    "name": "thelounge",
    "optionalDependencies": {
      "sqlite3": "5.0.0"
    },
    "preferGlobal": true,
    "repository": {
      "type": "git",
      "url": "git+https://github.com/thelounge/thelounge.git"
    },
    "scripts": {
      "build": "webpack",
      "coverage": "run-s test:* && nyc --nycrc-path=test/.nycrc-report.json report",
      "dev": "node index start --dev",
      "format:prettier": "prettier --write \"**/*.*\"",
      "lint:check-eslint": "eslint --print-config .eslintrc.yml | eslint-config-prettier-check",
      "lint:eslint": "eslint . --ext .js,.vue --report-unused-disable-directives --color",
      "lint:prettier": "prettier --list-different \"**/*.*\"",
      "lint:stylelint": "stylelint --color \"client/**/*.css\"",
      "start": "node index start",
      "test": "run-p --aggregate-output --continue-on-error lint:* test:*",
      "test:mocha": "webpack --config webpack.config-test.js && nyc --nycrc-path=test/.nycrc-mocha.json mocha --colors --config=test/.mocharc.yml",
      "watch": "webpack --watch"
    },
    "version": "4.2.0"
  }

yarn manifest:
  No manifest

Lockfile:
  No lockfile
```

**Comment by Emanon42** [comment]
Extra error: failed to fetch changelog
```
$ sudo systemctl status thelounge
● thelounge.service - The Lounge (IRC client)
     Loaded: loaded (/lib/systemd/system/thelounge.service; disabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-03-24 11:17:42 UTC; 23s ago
   Main PID: 47104 (node)
      Tasks: 11 (limit: 1073)
     Memory: 41.1M
     CGroup: /system.slice/thelounge.service
             └─47104 node /usr/bin/thelounge start

Mar 24 11:17:42 brachydios systemd[1]: Started The Lounge (IRC client).
Mar 24 11:17:44 brachydios thelounge[47104]: 2021-03-24 11:17:44 [ERROR] Unable to load node-sqlite3 module. See https://github.com/mapbox/node-sqlite3/wiki/Binaries
Mar 24 11:17:45 brachydios thelounge[47104]: 2021-03-24 11:17:45 [INFO] The Lounge v4.2.0 (Node.js 10.19.0 on linux x64)
Mar 24 11:17:45 brachydios thelounge[47104]: 2021-03-24 11:17:45 [INFO] Configuration file: /etc/thelounge/config.js
Mar 24 11:17:45 brachydios thelounge[47104]: 2021-03-24 11:17:45 [INFO] Available at http://[::]:9000/ in private mode
Mar 24 11:17:45 brachydios thelounge[47104]: 2021-03-24 11:17:45 [INFO] There are currently no users. Create one with thelounge add <name>.
Mar 24 11:17:45 brachydios thelounge[47104]: 2021-03-24 11:17:45 [ERROR] Failed to fetch changelog: RequestError: unable to get local issuer certificate
```

**Comment by xPaw** [comment]
The log shows you are using Node.js 10.19.0, so first of all update that. Then try running `update-ca-certificates` just to make sure.

Closing this as it isn't a TL issue.
