### ISSUE TITLE
Install fails with sqlite napi download

### ISSUE THREAD

**Issue by gullevek** [thelounge/thelounge-deb#82]
Deb package: thelounge_4.3.1-2_all.deb

403 error for the sqlite napi pacakge and then later some error because of the missing binary

```
Preparing to unpack .../thelounge_4.3.1-2_all.deb ...
Unpacking thelounge (4.3.1-2) ...
Setting up thelounge (4.3.1-2) ...
Downloading or building sqlite3 module for your specific installation
This might take several minutes, depending on your processor speed
/usr/lib/thelounge/node_modules/sqlite3 /
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@19.9.0 | linux | arm64
node-pre-gyp info ok
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@19.9.0 | linux | arm64
node-pre-gyp info check checked for "/usr/lib/thelounge/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
node-pre-gyp ERR! install response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.2 and node@19.9.0 (node-v111 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@19.9.0 | linux | arm64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@19.9.0 | linux | arm64
gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v19.9.0/node-v19.9.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v19.9.0/node-v19.9.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v19.9.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v19.9.0/SHASUMS256.txt
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
gyp ERR! stack     at createConfigFile (/usr/lib/thelounge/node_modules/node-gyp/lib/configure.js:117:21)
gyp ERR! stack     at /usr/lib/thelounge/node_modules/node-gyp/lib/configure.js:84:9
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:185:23)
gyp ERR! System Linux 5.10.0-21-arm64
gyp ERR! command "/usr/bin/node" "/usr/lib/thelounge/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/thelounge/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/lib/thelounge/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /usr/lib/thelounge/node_modules/sqlite3
gyp ERR! node -v v19.9.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/thelounge/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/thelounge/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/thelounge/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/thelounge/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Linux 5.10.0-21-arm64
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/thelounge/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/thelounge/node_modules/sqlite3
node-pre-gyp ERR! node -v v19.9.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/thelounge/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/thelounge/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/thelounge/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (7)
dpkg: error processing package thelounge (--configure):
 installed thelounge package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 thelounge
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by gullevek** [comment]
Must add that this is because of ARM architecture ...

**Comment by brunnre8** [comment]
It's not about a missing binary. That part is fine.
You have some traceback in the compilation function afterwards that's the problem.

If you are feeling adventurous, please try with our pre release instead, that bumped the sqlite version

https://github.com/thelounge/thelounge-deb/releases/tag/v4.4.0-pre.2

**Comment by gullevek** [comment]
That will need some more fixing around on my side because Debian 10 does not support zstd yet

https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg

```
Get:1 /var/local/downloads/thelounge_4.4.0.pre.2_all.deb thelounge all 4.4.0~pre.2 [9,883 kB]
dpkg-deb: error: archive '/var/local/downloads/thelounge_4.4.0.pre.2_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/local/downloads/thelounge_4.4.0.pre.2_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/local/downloads/thelounge_4.4.0.pre.2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by gullevek** [comment]
I just want to comment that if I run the fix for this 

```PACKAGE="thelounge_4.4.0.pre.2_all.deb"
PACKAGE_OUT="thelounge_4.4.0.pre.2_all.OUT.deb"
ar x ${PACKAGE}
zstd -d < control.tar.zst | xz > control.tar.xz
zstd -d < data.tar.zst | xz > data.tar.xz
ar -m -c -a sdsd ${PACKAGE_OUT} debian-binary control.tar.xz data.tar.xz
rm debian-binary control.tar.xz data.tar.xz control.tar.zst data.tar.zst
```
The install works:

```
Preparing to unpack .../thelounge_4.4.0.pre.2_all.OUT.deb ...
Unpacking thelounge (4.4.0~pre.2) ...
Setting up thelounge (4.4.0~pre.2) ...
Downloading or building sqlite3 module for your specific installation
This might take several minutes, depending on your processor speed
/usr/lib/thelounge/node_modules/sqlite3 /
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@19.9.0 | linux | arm64
node-pre-gyp info ok
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@19.9.0 | linux | arm64
node-pre-gyp info check checked for "/usr/lib/thelounge/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.6/napi-v6-linux-glibc-arm64.tar.gz
node-pre-gyp info install unpacking napi-v6-linux-glibc-arm64/node_sqlite3.node
node-pre-gyp info extracted file count: 1
[sqlite3] Success: "/usr/lib/thelounge/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm64/node_sqlite3.node" is installed via remote
node-pre-gyp info ok
/
Creating thelounge group
Creating thelounge user
Created symlink /etc/systemd/system/multi-user.target.wants/thelounge.service → /lib/systemd/system/thelounge.service.
```

**Comment by gullevek** [comment]
(DEBIAN 11 not 10)

apparently zstd support comes in Debian 12 bookworm

**Comment by brunnre8** [comment]
you gotta be kidding me... effing debian.

Means we need to change the builder to something older...

**Comment by gullevek** [comment]
4.4.0-rc1 can be installed normally on a debian system 11

**Comment by brunnre8** [comment]
thanks for checking
